config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  root 'static_pages#home'
  match '/about',     to: 'static_pages#about',     via: 'get'
  match '/donate',    to: 'static_pages#donate',    via: 'get'
  match '/search',    to: 'static_pages#search',    via: 'get'
  match '/thanks',    to: 'static_pages#thanks',    via: 'get'
  match '/feed',      to: 'static_pages#feed',      format: 'atom', via: 'get'
  match '/instant_articles', to: 'static_pages#instant_articles',      format: 'rss', via: 'get'
  match "/sitemap",   to: 'static_pages#sitemap',   format: 'xml',  via: 'get'

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  resources :articles, only: [:show, :index] do
    get :presses, on: :collection
    get :activities, on: :collection
    get :comments, on: :collection
    get :epapers, on: :collection
    get :books, on: :collection
  end
  resources :keywords, only: [:show]
  resources :epapers, only: [:show, :index]
  namespace :admin do
    root 'admins#index',             via: 'get', as: 'admin'
    resources :articles, except: [:show]
    resources :users, only: [:index, :update]
    resources :catalogs, except: [:show] do
      put :sort, on: :collection
    end
    resources :categories, except: [:show] do
      put :sort, on: :collection
    end
    resources :keywords, except: [:show] do
      get :order, on: :collection
      get :show_order, on: :collection
      put :sort,  on: :collection
      put :show_sort,  on: :collection
      resources :faqs, only: [:index]
    end
    match 'faqs/sort',   to: 'faqs#sort',   via: 'put'
    match 'slides/sort', to: 'slides#sort', via: 'put'
  end

  namespace :api, defaults: { format: 'json' } do
    resources :articles, only: [:show, :index]
    resources :keywords, only: [:show, :index]
    resources :catalogs, only: [:show, :index]
  end

  match "/404" => "errors#error404", via: [ :get, :post, :patch, :delete ], as: 'not_found'
  match "/422" => "errors#error422", via: [ :get, :post, :patch, :delete ]
  match "/500" => "errors#error500", via: [ :get, :post, :patch, :delete ]

  get '/api' => redirect('/swagger/dist/index.html?url=/apidocs/api-docs.json')

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @keywords = Keyword.showed
    @articles = Article.includes(:keywords).published.page(params[:page]).per(6)
    @epaper_article = Article.epapers.first
    @book_articles = Article.books
  end

  def search
    q = params[:q]
    @articles = Article.published.search(title_or_content_cont: q).result.page(params[:page])
    # @videos = Video.published.search(title_or_content_cont: q).result.page(params[:videos_page])
    # @kinds = []
    # @articles.each do |a|
    #   unless @kinds.include? a.kind
    #     @kinds << a.kind if a.kind
    #   end
    # end
    # puts @kinds
    set_meta_tags({
      title: "搜尋文章",
      og: {
        title: "搜尋文章"
      }
    })
  end

  def about
    @article = Article.where(kind: 'system', system_type: 'about').first
    set_meta_tags({
      title: "關於我們",
      og: {
        title: "關於我們",
        image: @article.image.blank? ? "#{Setting.url.protocol}://#{Setting.url.host}/images/jrf-img.png" : "#{Setting.url.protocol}://#{Setting.url.host}#{@article.image}"
      },
      article: {
        author: 'https://www.facebook.com/jrf.tw',
        published_time: @article.published_at.strftime('%FT%T%:z'),
        modified_time: @article.updated_at.strftime('%FT%T%:z')
      },
      twitter: {
        image: @article.image.blank? ? "#{Setting.url.protocol}://#{Setting.url.host}/images/jrf-img.png" : "#{Setting.url.protocol}://#{Setting.url.host}#{@article.image}",
      }
    })
  end

  def donate
    @article = Article.where(kind: 'system', system_type: 'donate').first
    set_meta_tags({
      title: "捐款支持",
      og: {
        title: "捐款支持",
        image: @article.image.blank? ? "#{Setting.url.protocol}://#{Setting.url.host}/images/jrf-img.png" : "#{Setting.url.protocol}://#{Setting.url.host}#{@article.image}"
      },
      article: {
        author: 'https://www.facebook.com/jrf.tw',
        published_time: @article.published_at.strftime('%FT%T%:z'),
        modified_time: @article.updated_at.strftime('%FT%T%:z')
      },
      twitter: {
        image: @article.image.blank? ? "#{Setting.url.protocol}://#{Setting.url.host}/images/jrf-img.png" : "#{Setting.url.protocol}://#{Setting.url.host}#{@article.image}",
      }
    })
  end

  def thanks
    set_meta_tags({
      title: "感謝您的支持",
      og: {
        title: "感謝您的支持",
        image: "#{Setting.url.protocol}://#{Setting.url.host}/images/thanks.png"
      },
      twitter: {
        image: "#{Setting.url.protocol}://#{Setting.url.host}/images/thanks.png"
      }
    })
  end

  def sitemap
    @articles = Article.published
    @keywords = Keyword.published
  end

  def feed
    @articles = Article.published
    respond_to do |format|
      format.atom { render :layout => false }
    end
  end

  def instant_articles
    @articles = Article.published
    respond_to do |format|
      format.rss { render :layout => false }
    end
  end
end

app/views/static_pages/_article.html.slim
doctype html
html lang="zh-Hant-TW" prefix="op: http://media.facebook.com/op#"
  head
    meta charset="utf-8"
    link href="#{article_url(article)}" rel="canonical"
    meta content="v1.0" property="op:markup_version"
  body
    article
      header
        h1 = article.title
        time.op-published datetime="#{article.published_at.to_s(:rfc822)}" = article.published_at('%Y年%m月%d日 %H:%i')
        time.op-modified datetime="#{article.updated_at.to_s(:rfc822)}" = article.updated_at('%Y年%m月%d日 %H:%i')
        address
          a = article.author
        
        - if article.youtube_id
          figure.op-social
            iframe src="//www.youtube.com/embed/#{article.youtube_id}?rel=0&wmode=opaque"
        - elsif article.image.blank?
          figure
            img src="#{image_url('jrf-img.png')}"
        - else
          figure
            img src="#{image_url(article.image)}"
      = article.content
      footer
        aside 財團法人民間司法改革基金會
        small CC-BY-SA 4.0

app/views/static_pages/_article.slim
doctype html
html lang="zh-Hant-TW" prefix="op: http://media.facebook.com/op#"
  head
    meta charset="utf-8"
    meta content="v1.0" property="op:markup_version"
    link href="#{article_url(article)}" rel="canonical"
    meta property="fb:article_style" content="default"
    title = article.title
  body
    article
      header
        h1 = article.title
        time.op-published datetime="#{article.published_at.to_s(:iso8601)}" = article.published_at.strftime('%Y年%m月%d日 %H:%M')
        time.op-modified datetime="#{article.updated_at.to_s(:iso8601)}" = article.updated_at.strftime('%Y年%m月%d日 %H:%M')
        address
          a = article.author
        - if article.youtube_id
          figure.op-social
            iframe src="https://www.youtube.com/embed/#{article.youtube_id}"
        - elsif article.image.blank?
          figure
            img src="#{image_url('jrf-img.png')}"
        - else
          figure
            img src="#{image_url(article.image)}"
      = article.fb_ia_content.try :html_safe
      footer
        aside 財團法人民間司法改革基金會
        small CC-BY-SA 4.0

app/views/static_pages/about.html.slim
.container
  .row.col-lg-12 data-animation-effect="fadeInUpSmall" data-effect-delay="200"
    - if @article.present?
      p.text-center
        .embed-responsive.embed-responsive-16by9
          - if @article.youtube_id
            iframe.embed-responsive-item src="//www.youtube.com/embed/#{@article.youtube_id}?rel=0&wmode=opaque"
          - else
            = image_tag(@article.image.banner, width: "100%", alt: "")
      h1.title.text-center = @article.title
      = @article.content.try(:html_safe)

app/views/static_pages/donate.html.slim
.container
  .row.col-lg-12 data-animation-effect="fadeInUpSmall" data-effect-delay="200"
    - if @article.present?
      p.text-center
        = image_tag(@article.image.banner, width: "100%", alt: "")
      h1.title.text-center = @article.title
      = @article.content.try(:html_safe)

app/views/static_pages/home.html.slim
.banner.hidden-xs
  .slideshow
    .slider-banner-container
      .slider-banner-fullscreen
        ul
          - @keywords.each do |k|
            li.dark-translucent-bg data-transition="fade" data-slotamount="7" data-masterspeed="500" data-saveperformance="on" data-title="#{k.name}"
              = image_tag k.cover.try(:url), alt: k.name, data: {bgposition: "center top", bgfit: "cover", bgrepeat: "no-repeat"}
              .tp-caption.very_large_text.sft.tp-resizeme data-x="center" data-y="0" data-speed="700" data-start="200" data-end="10000" data-endspeed="600"
                h1 = k.title
              .tp-caption.small_thin_white.sfb.tp-resizeme data-x="center" data-y="100" data-speed="700" data-start="400" data-end="10000" data-endspeed="600"
                = k.description.try(:html_safe)
                p.text-center
                  = link_to keyword_path(k), class: "btn btn-white btn-lg" do
                    | 了解更多
                    i.fa.fa-angle-right.pl-10

.page-top.gray-bg.hidden-xs
  .container
    .row
      .col-md-8.col-md-offset-2
        .call-to-action
          h1.title 實際行動，支持司改
          p
            | 每一個
            strong 你
            | ，都是點亮司法黑暗的一盞燭光
          .row.col-md-12
            .col-xs-4.col-sm-4.col-md-4
              .overlay-container
                = image_tag('v_lawer.png', alt: "義務律師")
                = link_to image_tag('v_lawer_word.png', class: "overlay img-circle"), "https://jrf.neticrm.tw/civicrm/profile/create?gid=34&reset=1", target: "_blank"
            .col-xs-4.col-sm-4.col-md-4
              .overlay-container
                = image_tag('v_donation.png', alt: "捐款支持")
                = link_to image_tag('v_donation_word.png', class: "overlay img-circle"), donate_path(anchor: "online")
            .col-xs-4.col-sm-4.col-md-4
              .overlay-container
                = image_tag('v_join.png', alt: "加入志工")
                = link_to image_tag('v_join_word.png', class: "overlay img-circle"), "https://jrf.neticrm.tw/civicrm/profile/create?gid=11&reset=1", target: "_blank"

.white-bg.section.object-non-visible data-animation-effect="fadeInUpSmall" data-effect-delay="100" 
  .container
    .row.col-md-12
      h2
        i.fa.fa-bullhorn
        | 最新訊息
      .separator-2
      /! masonry grid start
      .masonry-grid.isotope-container.row
        - @articles.each do |a|
          = render partial: 'shared/article_block', locals: { a: a }
    p.text-center
      = link_to articles_path, class: "btn btn-default btn-lg" do
        | 更多消息
        i.fa.fa-angle-right.pl-10

.gray-bg.section.object-non-visible data-animation-effect="fadeInUpSmall" data-effect-delay="100" 
  .container
    - if @epaper_article
      .row
        .col-md-6
          h2.page-title
            i.fa.fa-newspaper-o
            | 電子報
          .separator-2
          h3 = link_to @epaper_article.title, article_path(@epaper_article)
          = display_shorter(@epaper_article.content, 100)
          h4.text-left
            = link_to "更多電子報", epapers_articles_path, class: "btn btn-default"
            = link_to "訂閱電子報", "https://jrf.neticrm.tw/civicrm/profile/create?gid=12&reset=1", class: "btn btn-white", target: "_blank"
        aside.sidebar.col-md-6
          .side
            .block.clearfix
              .embed-responsive.embed-responsive-16by9
                = link_to image_tag(@epaper_article.image, class: "embed-responsive-item"), article_path(@epaper_article)

    - if @book_articles.any?
      .row
        .col-md-12
          h2.page-title
            i.fa.fa-book
            | 書籍
          .separator-2
          .owl-carousel.clients
            - num = 0
            - @book_articles.each do |a|
              - num += 1
              .client
                - if a.image.blank?
                  = link_to image_tag("jrf-img.png", alt: a.title), article_path(a)
                - else
                  = link_to image_tag(a.image.thumb, alt: a.title), article_path(a)
                h4.text-center = a.title
        h4.text-left
          = link_to "更多書籍", books_articles_path, class: "btn btn-default"
          = link_to "瀏覽GitBook", "https://www.gitbook.com/@jrf-tw", class: "btn btn-white", target: "_blank"

app/views/static_pages/search.html.slim
.container
  .row.col-lg-12 data-animation-effect="fadeInUpSmall" data-effect-delay="200"
    h1.title.text-center 搜尋：#{@query}
    .separator

- if @articles.any?
  .container
    .separator-2
    .filters
      ul.nav.nav-tabs
        - if @kind.blank?
          li.active
            = link_to "所有", url_for(params.merge({k: nil}))
          li
            = link_to "新聞稿", url_for(params.merge({k: "presses"}))
          li
            = link_to "活動", url_for(params.merge({k: "activities"}))
          li
            = link_to "活動", url_for(params.merge({k: "comments"}))
          li
            = link_to "電子報", url_for(params.merge({k: "epapers"}))
          li
            = link_to "書籍", url_for(params.merge({k: "books"}))
        - else
          li
            = link_to "所有", url_for(params.merge({k: nil}))
          - if @kind == 'presses'
            li.active
              = link_to "新聞稿", url_for(params.merge({k: "presses"}))
          - else
            li
              = link_to "新聞稿", url_for(params.merge({k: "presses"}))
          - if @kind == 'activities'
            li.active
              = link_to "活動", url_for(params.merge({k: "activities"}))
          - else
            li
              = link_to "活動", url_for(params.merge({k: "activities"}))
          - if @kind == 'comments'
            li.active
             = link_to "活動", url_for(params.merge({k: "comments"}))
          - else
            li
              = link_to "活動", url_for(params.merge({k: "comments"}))
          - if @kind == 'epapers'
            li.active
              = link_to "電子報", url_for(params.merge({k: "epapers"}))
          - else
            li
              = link_to "電子報", url_for(params.merge({k: "epapers"}))
          - if @kind == 'books'
            li.active
              = link_to "書籍", url_for(params.merge({k: "books"}))
          - else
            li
              = link_to "書籍", url_for(params.merge({k: "books"}))
    .row
      .block.clearfix.isotope-container
        - @articles.each do |a|
          .list-with-image.isotope-item.col-md-4 class="jrf-#{a.kind}"
            .overlay-container
              - unless a.youtube_id.blank?
                iframe.embed-responsive-item sec="//www.youtube.com/embed/#{a.youtube_id}"
              - else
                = image_tag(a.image, alt: "")
              = link_to article_path(a), class: "overlay small" do
                i.fa.fa-link
                span = a.kind.name
            h2
              = link_to a.title, article_path(a)
            p.small a.published_at.strftime('%Y-%m-%d')
    .row.text-center
      .col-md-10.col-md-offset-1
        = paginate @articles

app/views/static_pages/thanks.html.slim
section.main-container.gray-bg
  .container
    .row
      .main.col-md-6.col-md-offset-3
        h1.text-center Thanks！
        p
          = image_tag('thanks.png', width: '100%')
        p.text-center
          = link_to '返回首頁', root_path, class: 'btn btn-default'