config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  root 'static_pages#home'
  match '/about',     to: 'static_pages#about',     via: 'get'
  match '/donate',    to: 'static_pages#donate',    via: 'get'
  match '/search',    to: 'static_pages#search',    via: 'get'
  match '/thanks',    to: 'static_pages#thanks',    via: 'get'
  match '/feed',      to: 'static_pages#feed',      format: 'atom', via: 'get'
  match '/instant_articles', to: 'static_pages#instant_articles',      format: 'rss', via: 'get'
  match "/sitemap",   to: 'static_pages#sitemap',   format: 'xml',  via: 'get'

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  resources :articles, only: [:show, :index] do
    get :presses, on: :collection
    get :activities, on: :collection
    get :comments, on: :collection
    get :epapers, on: :collection
    get :books, on: :collection
  end
  resources :keywords, only: [:show]
  resources :epapers, only: [:show, :index]
  namespace :admin do
    root 'admins#index',             via: 'get', as: 'admin'
    resources :articles, except: [:show]
    resources :users, only: [:index, :update]
    resources :catalogs, except: [:show] do
      put :sort, on: :collection
    end
    resources :categories, except: [:show] do
      put :sort, on: :collection
    end
    resources :keywords, except: [:show] do
      get :order, on: :collection
      get :show_order, on: :collection
      put :sort,  on: :collection
      put :show_sort,  on: :collection
      resources :faqs, only: [:index]
    end
    match 'faqs/sort',   to: 'faqs#sort',   via: 'put'
    match 'slides/sort', to: 'slides#sort', via: 'put'
  end

  namespace :api, defaults: { format: 'json' } do
    resources :articles, only: [:show, :index]
    resources :keywords, only: [:show, :index]
    resources :catalogs, only: [:show, :index]
  end

  match "/404" => "errors#error404", via: [ :get, :post, :patch, :delete ], as: 'not_found'
  match "/422" => "errors#error422", via: [ :get, :post, :patch, :delete ]
  match "/500" => "errors#error500", via: [ :get, :post, :patch, :delete ]

  get '/api' => redirect('/swagger/dist/index.html?url=/apidocs/api-docs.json')

end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < Admin::BaseController
  before_action :set_article, except: [:index, :new]

  # GET /articles
  def index
    @q = Article.includes(:keywords).search(params[:q])
    @articles = @q.result(distinct: true).page(params[:page])
    set_meta_tags({
      title: "文章管理"
    })
  end

  # GET /articles/1
  def show
    @slides = @article.slides.all
  end

  # GET /articles/new
  def new
    @article = Article.new
    set_meta_tags({
      title: "新增文章"
    })
  end

  # GET /articles/1/edit
  def edit
    set_meta_tags({
      title: "編輯文章"
    })
  end

  # POST /articles
  def create
    if @article.save
      redirect_to admin_articles_url, notice: '文章建立成功'
    else
      render :new
    end
  end

  # PATCH/PUT /articles/1
  def update
    if @article.update(article_params)
      redirect_to admin_articles_url, notice: '文章更新成功'
    else
      render :edit
    end
  end

  # DELETE /articles/1
  def destroy
    @article.destroy
    redirect_to admin_articles_url, notice: '文章已刪除'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_article
    @article = params[:id] ? Article.find(params[:id]) : Article.new(article_params)
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def article_params
    params.require(:article).permit(:published, {keyword_ids: []}, :description, :author,
      :published_at, :kind, :image, :image_cache, :remove_image, :title, :content, :youtube_url, :link,
      slides_attributes: [:id, :slideable_id, :slideable_type, :image, :image_cache, :remove_image, :_destroy])
  end
end

app/controllers/api/articles_controller.rb
class Api::ArticlesController < ApplicationController
  respond_to :json

  swagger_controller :articles, 'Articles'

  swagger_api :index do
    summary '文章列表'
    notes '回應、查詢文章列表'
    param :query, :query, :string, :optional, "查詢標題、內容或作者"
    param :query, :limit, :integer, :optional, "一次顯示多少筆"
    param :query, :kind, :string, :optional, "文章種類"
    param :query, :offset, :integer, :optional, "從第幾筆開始顯示"
    param :query, :date_start, :string, :optional, "顯示哪個日期以後的文章"
    param :query, :date_end, :string, :optional, "顯示哪個日期以前的文章"
    response :ok, "Success", :APIArticleIndex
  end

  def index
    limit = params[:limit].blank? ? 10 : params[:limit]
    ransack_params = {}
    ransack_params[:kind_eq] = params[:kind] if params[:kind]
    ransack_params[:title_or_content_or_author_cont] = params[:query] if params[:query]
    ransack_params[:published_at_gt] = params[:date_start] if params[:date_start]
    ransack_params[:published_at_lt] = params[:date_end] if params[:date_end]
    if ransack_params.blank?
      @articles = Article.includes(:keywords).offset(params[:offset]).limit(limit)
      @articles_count = Article.count
    else
      @articles = Article.includes(:keywords).ransack(ransack_params).result(distinct: true)
        .offset(params[:offset]).limit(limit)
      @articles_count = Article.ransack(ransack_params).result(distinct: true).count
    end
    respond_with(@articles, @articles_count)
  end

  swagger_api :show do
    summary '單一文章'
    notes '回應單一文章資訊'
    param :path, :id, :integer, :optional, "文章 Id"
    response :ok, "Success", :APIArticleShow
    response :not_found
  end

  def show
    @article = Article.includes(:keywords).find(params[:id])
    respond_with(@article)
  end

  swagger_model :APIArticleIndex do
    description "Article show structure"
    property :count, :integer, :required, "文章數"
    property :articles, :array, :required, "文章列表", items: { '$ref' => :Article }
    property :status, :string, :required, "狀態"
  end

  swagger_model :APIArticleShow do
    description "Article show structure"
    property :article, nil, :required, "文章", '$ref' => :Article
    property :status, :string, :required, "狀態"
  end

  swagger_model :Article do
    description "文章"
    property :id, :integer, :required, "文章 Id"
    property :title, :string, :required, "標題"
    property :author, :string, :required, "作者"
    property :content, :string, :required, "內文"
    property :kind, :string, :required, "文章種類"
    property :image, :string, :required, "圖片網址"
    property :youtube_url, :string, :optional, "Youtube 網址"
    property :youtube_id, :string, :optional, "Youtube ID"
    property :description, :string, :optional, "簡短描述"
    property :published_at, :date, :required, "發佈時間"
    property :created_at, :date, :required, "建立時間"
    property :updated_at, :date, :required, "更新時間"
    property :keywords, :array, :required, '關鍵字清單', items: { '$ref' => :SimpleKeyword }
  end

  swagger_model :SimpleKeyword do
    description "關鍵字"
    property :id, :integer, :required, "關鍵字 Id"
    property :name, :string, :required, "關鍵字名稱"
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, except: [:index, :new, :presses, :activities, :comments, :epapers, :books]
  #before_action :authenticate_user!, except: [:show, :index]

  # GET /articles
  def index
    if params[:format] == "json"
      if params[:query]
        @articles = Article.includes(:keywords).published.ransack({title_or_content_cont: params[:query]}).result(distinct: true)
          .published.offset(params[:offset]).limit(params[:limit])
        @articles_count = Article.includes(:keywords).published.ransack({title_or_content_cont: params[:query]}).result(distinct: true)
          .published.count
      else
        @articles = Article.includes(:keywords).published.offset(params[:offset]).limit(params[:limit])
        @articles_count = Article.includes(:keywords).published.count
      end
    else
      if user_signed_in? and current_user.admin?
        @q = Article.includes(:keywords).search(params[:q])
        @articles = @q.result(distinct: true).page(params[:page])
      else
        @q = Article.includes(:keywords).published.search(params[:q])
        @articles = @q.result(distinct: true).page(params[:page])
      end
    end
    set_meta_tags({
      title: "所有文章",
      og: {
        title: "所有文章"
      }
    })

    respond_to do |format|
      format.html
      format.json { render json: {
        status: "success",
        articles: @articles.as_json(include: [:keywords], except: [:published]),
        count: @articles_count
      },
      callback: params[:callback]
      }
    end
  end

  def presses
    if params[:format] == "json"
      if params[:query]
        @articles = Article.includes(:keywords).presses.published.ransack({title_or_content_cont: params[:query]}).result(distinct: true)
          .offset(params[:offset]).limit(params[:limit])
        @articles_count = Article.includes(:keywords).presses.published.ransack({title_or_content_cont: params[:query]}).result(distinct: true)
          .count
      else
        @articles = Article.includes(:keywords).presses.published.offset(params[:offset]).limit(params[:limit])
        @articles_count = Article.includes(:keywords).presses.published.count
      end
    else
      if user_signed_in? and current_user.admin?
        @q = Article.includes(:keywords).presses.search(params[:q])
      else
        @q = Article.includes(:keywords).presses.published.search(params[:q])
      end
      @articles = @q.result(distinct: true).page(params[:page])
    end
    set_meta_tags({
      title: "新聞稿",
      og: {
        title: "新聞稿"
      }
    })
    respond_to do |format|
      format.html
      format.json { render json: {
        status: "success",
        articles: @articles.as_json(include: [:keywords], except: [:published]),
        count: @articles_count
      },
      callback: params[:callback]
      }
    end
  end

  def activities
    if params[:format] == "json"
      if params[:query]
        @articles = Article.includes(:keywords).activities.published.ransack({title_or_content_cont: params[:query]}).result(distinct: true)
          .offset(params[:offset]).limit(params[:limit])
        @articles_count = Article.includes(:keywords).activities.published.ransack({title_or_content_cont: params[:query]}).result(distinct: true)
          .count
      else
        @articles = Article.includes(:keywords).activities.published.offset(params[:offset]).limit(params[:limit])
        @articles_count = Article.includes(:keywords).activities.published.count
      end
    else
      if user_signed_in? and current_user.admin?
        @q = Article.includes(:keywords).activities.search(params[:q])
      else
        @q = Article.includes(:keywords).activities.published.search(params[:q])
      end
      @articles = @q.result(distinct: true).page(params[:page])
    end
    set_meta_tags({
      title: "最新活動",
      og: {
        title: "最新活動"
      }
    })
    respond_to do |format|
      format.html
      format.json { render json: {
        status: "success",
        articles: @articles.to_json(include: [:keywords], except: [:published]),
        count: @articles_count
      },
      callback: params[:callback]
      }
    end
  end

  def comments
    if params[:format] == "json"
      if params[:query]
        @articles = Article.includes(:keywords).comments.published.ransack({title_or_content_cont: params[:query]}).result(distinct: true)
          .offset(params[:offset]).limit(params[:limit])
        @articles_count = Article.includes(:keywords).comments.published.ransack({title_or_content_cont: params[:query]}).result(distinct: true)
          .count
      else
        @articles = Article.includes(:keywords).comments.published.offset(params[:offset]).limit(params[:limit])
        @articles_count = Article.includes(:keywords).comments.published.count
      end
    else
      if user_signed_in? and current_user.admin?
        @q = Article.includes(:keywords).comments.search(params[:q])
      else
        @q = Article.includes(:keywords).comments.published.search(params[:q])
      end
      @articles = @q.result(distinct: true).page(params[:page])
    end
    set_meta_tags({
      title: "評論文章",
      og: {
        title: "評論文章"
      }
    })
    respond_to do |format|
      format.html
      format.json { render json: {
        status: "success",
        articles: @articles.as_json(include: [:keywords], except: [:published]),
        count: @articles_count
      },
      callback: params[:callback]
      }
    end
  end

  def epapers
    if params[:format] == "json"
      if params[:query]
        @articles = Article.includes(:keywords).epapers.published.ransack({title_or_content_cont: params[:query]}).result(distinct: true)
          .offset(params[:offset]).limit(params[:limit])
        @articles_count = Article.includes(:keywords).epapers.published.ransack({title_or_content_cont: params[:query]}).result(distinct: true)
          .count
      else
        @articles = Article.includes(:keywords).epapers.published.offset(params[:offset]).limit(params[:limit])
        @articles_count = Article.includes(:keywords).epapers.published.count
      end
    else
      if user_signed_in? and current_user.admin?
        @q = Article.includes(:keywords).epapers.search(params[:q])
      else
        @q = Article.includes(:keywords).epapers.published.search(params[:q])
      end
      @articles = @q.result(distinct: true).page(params[:page])
    end
    set_meta_tags({
      title: "電子報",
      og: {
        title: "電子報"
      }
    })
    respond_to do |format|
      format.html
      format.json { render json: {
        status: "success",
        articles: @articles.as_json(include: [:keywords], except: [:published]),
        count: @articles_count
      },
      callback: params[:callback]
      }
    end
  end

  def books
    if params[:format] == "json"
      if params[:query]
        @articles = Article.includes(:keywords).books.published.ransack({title_or_content_cont: params[:query]}).result(distinct: true)
          .offset(params[:offset]).limit(params[:limit])
        @articles_count = Article.includes(:keywords).books.published.ransack({title_or_content_cont: params[:query]}).result(distinct: true)
          .count
      else
        @articles = Article.includes(:keywords).books.published.offset(params[:offset]).limit(params[:limit])
        @articles_count = Article.includes(:keywords).books.published.count
      end
    else
      if user_signed_in? and current_user.admin?
        @q = Article.includes(:keywords).books.search(params[:q])
      else
        @q = Article.includes(:keywords).books.published.search(params[:q])
      end
      @articles = @q.result(distinct: true).page(params[:page])
    end
    set_meta_tags({
      title: "出版品",
      og: {
        title: "出版品"
      }
    })
    respond_to do |format|
      format.html
      format.json { render json: {
        status: "success",
        articles: @articles.as_json(include: [:keywords], except: [:published]),
        count: @articles_count
      },
      callback: params[:callback]
      }
    end
  end

  # GET /articles/1
  def show
    keywords = @article.keywords.to_a.map{ |k| k.name }.join(',')
    if @article.keywords.first
      @related_articles = @article.keywords.first.articles.published.first(4).reject { |a| [@article].include? a }
      if @related_articles.length > 3
        @related_articles = @related_articles.first(3)
      end
    else
      @related_articles = []
    end
    @lastest_articles = Article.published.first(3)
    set_meta_tags({
      title: @article.title,
      description: sanitize(@article.description),
      keywords: keywords,
      og: {
        type: 'article',
        image: @article.image.blank? ? "#{Setting.url.protocol}://#{Setting.url.host}/images/jrf-img.png" : "#{Setting.url.protocol}://#{Setting.url.host}#{@article.image}",
        title: @article.title,
        description: sanitize(@article.description)
      },
      article: {
        author: Setting.url.fb,
        publisher: Setting.url.fb,
        published_time: @article.published_at.strftime('%FT%T%:z'),
        modified_time: @article.updated_at.strftime('%FT%T%:z')
      },
      twitter: {
        image: @article.image.blank? ? "#{Setting.url.protocol}://#{Setting.url.host}/images/jrf-img.png" : "#{Setting.url.protocol}://#{Setting.url.host}#{@article.image}",
      }
    })

    respond_to do |format|
      format.html
      format.json { render json: {
        status: "success",
        article: @article.as_json(include: [:keywords], except: [:published]),
        callback: params[:callback]
        }
      }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_article
    @article = params[:id] ? Article.find(params[:id]) : Article.new(article_params)
  end

  # Never trust parameters from the scary internet, only allow the white list through.

app/views/admin/articles/_form.html.slim
= render 'shared/error_messages', object: f.object
- unless @article.kind == 'system'
  .form-group
    = f.association :keywords, label: "專案分類", collection: Keyword.all, input_html: { class: 'chosen-select form-control' }
    = f.input :kind, label: "類型", collection: [['新聞稿', 'press'], ['活動', 'activity'], ['評論', 'comment'], ['電子報', 'epaper'], ['書籍', 'book']], input_html: { class: 'form-control' }, include_blank: false
  .form-group
    = f.input :title, label: '標題', required: true, input_html: { class: 'form-control' }, hint: "建議少於30字"
  .form-group
    = f.input :published_at, as: :string, label: '發布日期', input_html: { class: "datetimepicker" }, required: true
  .form-group
    = f.input :published, as: :boolean, label: '允許發布'
  .form-group
    = f.input :author, label: '作者', required: true, input_html: { class: 'form-control' }, hint: "多項時請以頓號（、）分開"
  .form-group
    = f.input :link, label: '連結', input_html: { class: 'form-control' }, hint: "如果是書本，請把書本連結填入"
  .form-group
    = f.input :image, as: :file, label: '圖示', required: true, input_html: { id: 'exampleInputFile' }, label_html: {for: "exampleInputFile"}
    = f.input :image_cache, as: :hidden
    = f.input :remove_image, as:  :boolean, label: '移除圖片'
    p.help-block 建議大小1600*900，將文章頁閱讀時顯示
    = image_tag(@article.image_url, alt:"") if @article.image?
  - unless @article.new_record?
    #slides.sortable-slide
      = f.simple_fields_for :slides do |slide|
        = render :partial => 'slide_fields', :locals => { :f => slide }
      = link_to_add_association "新增Slide", f, :slides, class: "btn radius btn-white btn-sm"
  .form-group
    = f.input :youtube_url, label: 'Youtube 網址', input_html: { class: 'form-control' }, hint: "Youtube 網址，若貼上則顯示youtube為主"
  .form-group
    label 簡述
    = f.cktext_area :description, required: true, hint: "此處文字在專案主打時出現在首頁中，以及供FB抓取"
    p.help-block 此處文字在專案主打時出現在首頁中，以供FB抓取
  .form-group
    label 內文
    = f.cktext_area :content, label: '內文', required: true
- else
  .form-group
    = f.association :keywords, label: "專案分類", collection: Keyword.all, input_html: { class: 'chosen-select form-control' }, disabled: true
    = f.input :kind, label: "類型", collection: [['系統', 'system']], input_html: { class: 'form-control' }, include_blank: false, disabled: true
  .form-group
    = f.input :title, label: '標題', required: true, input_html: { class: 'form-control' }, hint: "建議少於30字"
  .form-group
    = f.input :published_at, as: :string, label: '發布日期', input_html: { class: "datetimepicker" }, required: true, disabled: true
  .form-group
    = f.input :published, as: :boolean, label: '發布', disabled: true
  .form-group
    = f.input :author, label: '作者', required: true, input_html: { class: 'form-control' }, hint: "多項時請以頓號（、）分開", disabled: true
  .form-group
    = f.input :link, label: '連結', input_html: { class: 'form-control' }, hint: "如果是書本，請把書本連結填入", disabled: true
  .form-group
    = f.input :image, as: :file, label: '圖示', required: true, input_html: { id: 'exampleInputFile' }, label_html: {for: "exampleInputFile"}
    = f.input :image_cache, as: :hidden
    = f.input :remove_image, as:  :boolean, label: '移除圖片'
    p.help-block 建議大小1024*768，將文章頁閱讀時顯示
    = image_tag(@article.image_url, alt:"") if @article.image?
  - unless @article.new_record?
    #slides.sortable-slide
      = f.simple_fields_for :slides do |slide|
        = render :partial => 'admin/shared/slides_fields', :locals => { :f => slide }
      = link_to_add_association "新增Slide", f, :slides, class: "btn radius btn-white btn-sm"
  .form-group
    = f.input :youtube_url, label: 'Youtube 網址', input_html: { class: 'form-control' }
  .form-group
    label 簡述
    = f.cktext_area :description, required: true, hint: "此處文字在專案主打時出現在首頁中，以及供FB抓取"
    p.help-block 此處文字在專案主打時出現在首頁中，以供FB抓取
  .form-group
    label 內文
    = f.cktext_area :content, label: '內文', required: true
= f.button :submit, "儲存", class: 'btn btn-default'

app/views/admin/articles/_slide_fields.html.slim
.nested-fields.panel.panel-default.gray-bg data-id="#{f.object.id}"
  = f.input :image, as: :file, label: '附圖', input_html: { id: 'exampleInputFile' }, label_html: {for: "exampleInputFile"}
  = f.input :image_cache, as: :hidden
  = f.input :remove_image, as:  :boolean, label: '移除圖片'
  p.help-block 建議大小1600*900，將顯示為投影片
  = image_tag(f.object.image_url, alt:"") if f.object.image?
  = link_to_remove_association "刪除Slide圖片", f, class: "form-control"

app/views/admin/articles/edit.html.slim
h1 編輯文章
= simple_form_for @article, url: admin_article_path(@article), method: :put do |f|
  = render :partial => 'form', :locals => { :f => f }

app/views/admin/articles/index.html.slim
h1.text-center 修改/刪除文章
.form-group
  = search_form_for @q, url: admin_articles_path do |f|
    label 標題內容搜尋
    = f.search_field :title_or_content_cont, class: "form-control", placeholder: "輸入"
    = f.submit "搜尋", class: "btn btn-default radius btn-sm"
hr
table.table
  thead
    tr
      th ID
      th 標題
      th 關鍵字
      th 種類
      th 日期
      th 編輯/刪除
  tbody
    - @articles.each do |a|
      tr
        td = a.id
        td = a.title
        td
          - num = 0
          - a.keywords.each do |k|
            - if num == 0
              - num += 1
            - else
              | 、
            = link_to k.name, keyword_path(k)
        td = a.kind
        td = a.published_at.try(:strftime, '%Y-%m-%d')
        td
          = link_to '編輯', edit_admin_article_path(a), class: "btn radius btn-white btn-sm"
          = link_to '刪除', admin_article_path(a), method: :delete, data: { confirm: '確認要刪除嗎？' }, class: "btn radius btn-default btn-sm"

app/views/admin/articles/new.html.slim
h1.text-center 新增文章
= simple_form_for @article, url: admin_articles_path do |f|
  = render :partial => 'form', :locals => { :f => f }