config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  root 'static_pages#home'
  match '/about',     to: 'static_pages#about',     via: 'get'
  match '/donate',    to: 'static_pages#donate',    via: 'get'
  match '/search',    to: 'static_pages#search',    via: 'get'
  match '/thanks',    to: 'static_pages#thanks',    via: 'get'
  match '/feed',      to: 'static_pages#feed',      format: 'atom', via: 'get'
  match '/instant_articles', to: 'static_pages#instant_articles',      format: 'rss', via: 'get'
  match "/sitemap",   to: 'static_pages#sitemap',   format: 'xml',  via: 'get'

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  resources :articles, only: [:show, :index] do
    get :presses, on: :collection
    get :activities, on: :collection
    get :comments, on: :collection
    get :epapers, on: :collection
    get :books, on: :collection
  end
  resources :keywords, only: [:show]
  resources :epapers, only: [:show, :index]
  namespace :admin do
    root 'admins#index',             via: 'get', as: 'admin'
    resources :articles, except: [:show]
    resources :users, only: [:index, :update]
    resources :catalogs, except: [:show] do
      put :sort, on: :collection
    end
    resources :categories, except: [:show] do
      put :sort, on: :collection
    end
    resources :keywords, except: [:show] do
      get :order, on: :collection
      get :show_order, on: :collection
      put :sort,  on: :collection
      put :show_sort,  on: :collection
      resources :faqs, only: [:index]
    end
    match 'faqs/sort',   to: 'faqs#sort',   via: 'put'
    match 'slides/sort', to: 'slides#sort', via: 'put'
  end

  namespace :api, defaults: { format: 'json' } do
    resources :articles, only: [:show, :index]
    resources :keywords, only: [:show, :index]
    resources :catalogs, only: [:show, :index]
  end

  match "/404" => "errors#error404", via: [ :get, :post, :patch, :delete ], as: 'not_found'
  match "/422" => "errors#error422", via: [ :get, :post, :patch, :delete ]
  match "/500" => "errors#error500", via: [ :get, :post, :patch, :delete ]

  get '/api' => redirect('/swagger/dist/index.html?url=/apidocs/api-docs.json')

end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < Admin::BaseController
  before_action :set_article, except: [:index, :new]

  # GET /articles
  def index
    @q = Article.includes(:keywords).search(params[:q])
    @articles = @q.result(distinct: true).page(params[:page])
    set_meta_tags({
      title: "文章管理"
    })
  end

  # GET /articles/1
  def show
    @slides = @article.slides.all
  end

  # GET /articles/new
  def new
    @article = Article.new
    set_meta_tags({
      title: "新增文章"
    })
  end

  # GET /articles/1/edit
  def edit
    set_meta_tags({
      title: "編輯文章"
    })
  end

  # POST /articles
  def create
    if @article.save
      redirect_to admin_articles_url, notice: '文章建立成功'
    else
      render :new
    end
  end

  # PATCH/PUT /articles/1
  def update
    if @article.update(article_params)
      redirect_to admin_articles_url, notice: '文章更新成功'
    else
      render :edit
    end
  end

  # DELETE /articles/1
  def destroy
    @article.destroy
    redirect_to admin_articles_url, notice: '文章已刪除'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_article
    @article = params[:id] ? Article.find(params[:id]) : Article.new(article_params)
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def article_params
    params.require(:article).permit(:published, {keyword_ids: []}, :description, :author,
      :published_at, :kind, :image, :image_cache, :remove_image, :title, :content, :youtube_url, :link,
      slides_attributes: [:id, :slideable_id, :slideable_type, :image, :image_cache, :remove_image, :_destroy])
  end
end

app/controllers/api/articles_controller.rb
class Api::ArticlesController < ApplicationController
  respond_to :json

  swagger_controller :articles, 'Articles'

  swagger_api :index do
    summary '文章列表'
    notes '回應、查詢文章列表'
    param :query, :query, :string, :optional, "查詢標題、內容或作者"
    param :query, :limit, :integer, :optional, "一次顯示多少筆"
    param :query, :kind, :string, :optional, "文章種類"
    param :query, :offset, :integer, :optional, "從第幾筆開始顯示"
    param :query, :date_start, :string, :optional, "顯示哪個日期以後的文章"
    param :query, :date_end, :string, :optional, "顯示哪個日期以前的文章"
    response :ok, "Success", :APIArticleIndex
  end

  def index
    limit = params[:limit].blank? ? 10 : params[:limit]
    ransack_params = {}
    ransack_params[:kind_eq] = params[:kind] if params[:kind]
    ransack_params[:title_or_content_or_author_cont] = params[:query] if params[:query]
    ransack_params[:published_at_gt] = params[:date_start] if params[:date_start]
    ransack_params[:published_at_lt] = params[:date_end] if params[:date_end]
    if ransack_params.blank?
      @articles = Article.includes(:keywords).offset(params[:offset]).limit(limit)
      @articles_count = Article.count
    else
      @articles = Article.includes(:keywords).ransack(ransack_params).result(distinct: true)
        .offset(params[:offset]).limit(limit)
      @articles_count = Article.ransack(ransack_params).result(distinct: true).count
    end
    respond_with(@articles, @articles_count)
  end

  swagger_api :show do
    summary '單一文章'
    notes '回應單一文章資訊'
    param :path, :id, :integer, :optional, "文章 Id"
    response :ok, "Success", :APIArticleShow
    response :not_found
  end

  def show
    @article = Article.includes(:keywords).find(params[:id])
    respond_with(@article)
  end

  swagger_model :APIArticleIndex do
    description "Article show structure"
    property :count, :integer, :required, "文章數"
    property :articles, :array, :required, "文章列表", items: { '$ref' => :Article }
    property :status, :string, :required, "狀態"
  end

  swagger_model :APIArticleShow do
    description "Article show structure"
    property :article, nil, :required, "文章", '$ref' => :Article
    property :status, :string, :required, "狀態"
  end

  swagger_model :Article do
    description "文章"
    property :id, :integer, :required, "文章 Id"
    property :title, :string, :required, "標題"
    property :author, :string, :required, "作者"
    property :content, :string, :required, "內文"
    property :kind, :string, :required, "文章種類"
    property :image, :string, :required, "圖片網址"
    property :youtube_url, :string, :optional, "Youtube 網址"
    property :youtube_id, :string, :optional, "Youtube ID"
    property :description, :string, :optional, "簡短描述"
    property :published_at, :date, :required, "發佈時間"
    property :created_at, :date, :required, "建立時間"
    property :updated_at, :date, :required, "更新時間"
    property :keywords, :array, :required, '關鍵字清單', items: { '$ref' => :SimpleKeyword }
  end

  swagger_model :SimpleKeyword do
    description "關鍵字"
    property :id, :integer, :required, "關鍵字 Id"
    property :name, :string, :required, "關鍵字名稱"
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, except: [:index, :new, :presses, :activities, :comments, :epapers, :books]
  #before_action :authenticate_user!, except: [:show, :index]

  # GET /articles
  def index
    if params[:format] == "json"
      if params[:query]
        @articles = Article.includes(:keywords).published.ransack({title_or_content_cont: params[:query]}).result(distinct: true)
          .published.offset(params[:offset]).limit(params[:limit])
        @articles_count = Article.includes(:keywords).published.ransack({title_or_content_cont: params[:query]}).result(distinct: true)
          .published.count
      else
        @articles = Article.includes(:keywords).published.offset(params[:offset]).limit(params[:limit])
        @articles_count = Article.includes(:keywords).published.count
      end
    else
      if user_signed_in? and current_user.admin?
        @q = Article.includes(:keywords).search(params[:q])
        @articles = @q.result(distinct: true).page(params[:page])
      else
        @q = Article.includes(:keywords).published.search(params[:q])
        @articles = @q.result(distinct: true).page(params[:page])
      end
    end
    set_meta_tags({
      title: "所有文章",
      og: {
        title: "所有文章"
      }
    })

    respond_to do |format|
      format.html
      format.json { render json: {
        status: "success",
        articles: @articles.as_json(include: [:keywords], except: [:published]),
        count: @articles_count
      },
      callback: params[:callback]
      }
    end
  end

  def presses
    if params[:format] == "json"
      if params[:query]
        @articles = Article.includes(:keywords).presses.published.ransack({title_or_content_cont: params[:query]}).result(distinct: true)
          .offset(params[:offset]).limit(params[:limit])
        @articles_count = Article.includes(:keywords).presses.published.ransack({title_or_content_cont: params[:query]}).result(distinct: true)
          .count
      else
        @articles = Article.includes(:keywords).presses.published.offset(params[:offset]).limit(params[:limit])
        @articles_count = Article.includes(:keywords).presses.published.count
      end
    else
      if user_signed_in? and current_user.admin?
        @q = Article.includes(:keywords).presses.search(params[:q])
      else
        @q = Article.includes(:keywords).presses.published.search(params[:q])
      end
      @articles = @q.result(distinct: true).page(params[:page])
    end
    set_meta_tags({
      title: "新聞稿",
      og: {
        title: "新聞稿"
      }
    })
    respond_to do |format|
      format.html
      format.json { render json: {
        status: "success",
        articles: @articles.as_json(include: [:keywords], except: [:published]),
        count: @articles_count
      },
      callback: params[:callback]
      }
    end
  end

  def activities
    if params[:format] == "json"
      if params[:query]
        @articles = Article.includes(:keywords).activities.published.ransack({title_or_content_cont: params[:query]}).result(distinct: true)
          .offset(params[:offset]).limit(params[:limit])
        @articles_count = Article.includes(:keywords).activities.published.ransack({title_or_content_cont: params[:query]}).result(distinct: true)
          .count
      else
        @articles = Article.includes(:keywords).activities.published.offset(params[:offset]).limit(params[:limit])
        @articles_count = Article.includes(:keywords).activities.published.count
      end
    else
      if user_signed_in? and current_user.admin?
        @q = Article.includes(:keywords).activities.search(params[:q])
      else
        @q = Article.includes(:keywords).activities.published.search(params[:q])
      end
      @articles = @q.result(distinct: true).page(params[:page])
    end
    set_meta_tags({
      title: "最新活動",
      og: {
        title: "最新活動"
      }
    })
    respond_to do |format|
      format.html
      format.json { render json: {
        status: "success",
        articles: @articles.to_json(include: [:keywords], except: [:published]),
        count: @articles_count
      },
      callback: params[:callback]
      }
    end
  end

  def comments
    if params[:format] == "json"
      if params[:query]
        @articles = Article.includes(:keywords).comments.published.ransack({title_or_content_cont: params[:query]}).result(distinct: true)
          .offset(params[:offset]).limit(params[:limit])
        @articles_count = Article.includes(:keywords).comments.published.ransack({title_or_content_cont: params[:query]}).result(distinct: true)
          .count
      else
        @articles = Article.includes(:keywords).comments.published.offset(params[:offset]).limit(params[:limit])
        @articles_count = Article.includes(:keywords).comments.published.count
      end
    else
      if user_signed_in? and current_user.admin?
        @q = Article.includes(:keywords).comments.search(params[:q])
      else
        @q = Article.includes(:keywords).comments.published.search(params[:q])
      end
      @articles = @q.result(distinct: true).page(params[:page])
    end
    set_meta_tags({
      title: "評論文章",
      og: {
        title: "評論文章"
      }
    })
    respond_to do |format|
      format.html
      format.json { render json: {
        status: "success",
        articles: @articles.as_json(include: [:keywords], except: [:published]),
        count: @articles_count
      },
      callback: params[:callback]
      }
    end
  end

  def epapers
    if params[:format] == "json"
      if params[:query]
        @articles = Article.includes(:keywords).epapers.published.ransack({title_or_content_cont: params[:query]}).result(distinct: true)
          .offset(params[:offset]).limit(params[:limit])
        @articles_count = Article.includes(:keywords).epapers.published.ransack({title_or_content_cont: params[:query]}).result(distinct: true)
          .count
      else
        @articles = Article.includes(:keywords).epapers.published.offset(params[:offset]).limit(params[:limit])
        @articles_count = Article.includes(:keywords).epapers.published.count
      end
    else
      if user_signed_in? and current_user.admin?
        @q = Article.includes(:keywords).epapers.search(params[:q])
      else
        @q = Article.includes(:keywords).epapers.published.search(params[:q])
      end
      @articles = @q.result(distinct: true).page(params[:page])
    end
    set_meta_tags({
      title: "電子報",
      og: {
        title: "電子報"
      }
    })
    respond_to do |format|
      format.html
      format.json { render json: {
        status: "success",
        articles: @articles.as_json(include: [:keywords], except: [:published]),
        count: @articles_count
      },
      callback: params[:callback]
      }
    end
  end

  def books
    if params[:format] == "json"
      if params[:query]
        @articles = Article.includes(:keywords).books.published.ransack({title_or_content_cont: params[:query]}).result(distinct: true)
          .offset(params[:offset]).limit(params[:limit])
        @articles_count = Article.includes(:keywords).books.published.ransack({title_or_content_cont: params[:query]}).result(distinct: true)
          .count
      else
        @articles = Article.includes(:keywords).books.published.offset(params[:offset]).limit(params[:limit])
        @articles_count = Article.includes(:keywords).books.published.count
      end
    else
      if user_signed_in? and current_user.admin?
        @q = Article.includes(:keywords).books.search(params[:q])
      else
        @q = Article.includes(:keywords).books.published.search(params[:q])
      end
      @articles = @q.result(distinct: true).page(params[:page])
    end
    set_meta_tags({
      title: "出版品",
      og: {
        title: "出版品"
      }
    })
    respond_to do |format|
      format.html
      format.json { render json: {
        status: "success",
        articles: @articles.as_json(include: [:keywords], except: [:published]),
        count: @articles_count
      },
      callback: params[:callback]
      }
    end
  end

  # GET /articles/1
  def show
    keywords = @article.keywords.to_a.map{ |k| k.name }.join(',')
    if @article.keywords.first
      @related_articles = @article.keywords.first.articles.published.first(4).reject { |a| [@article].include? a }
      if @related_articles.length > 3
        @related_articles = @related_articles.first(3)
      end
    else
      @related_articles = []
    end
    @lastest_articles = Article.published.first(3)
    set_meta_tags({
      title: @article.title,
      description: sanitize(@article.description),
      keywords: keywords,
      og: {
        type: 'article',
        image: @article.image.blank? ? "#{Setting.url.protocol}://#{Setting.url.host}/images/jrf-img.png" : "#{Setting.url.protocol}://#{Setting.url.host}#{@article.image}",
        title: @article.title,
        description: sanitize(@article.description)
      },
      article: {
        author: Setting.url.fb,
        publisher: Setting.url.fb,
        published_time: @article.published_at.strftime('%FT%T%:z'),
        modified_time: @article.updated_at.strftime('%FT%T%:z')
      },
      twitter: {
        image: @article.image.blank? ? "#{Setting.url.protocol}://#{Setting.url.host}/images/jrf-img.png" : "#{Setting.url.protocol}://#{Setting.url.host}#{@article.image}",
      }
    })

    respond_to do |format|
      format.html
      format.json { render json: {
        status: "success",
        article: @article.as_json(include: [:keywords], except: [:published]),
        callback: params[:callback]
        }
      }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_article
    @article = params[:id] ? Article.find(params[:id]) : Article.new(article_params)
  end

  # Never trust parameters from the scary internet, only allow the white list through.

app/views/articles/activities.html.slim
.white-bg.object-non-visible data-animation-effect="fadeInUpSmall" data-effect-delay="100"
  .container
    .row.col-md-12
      .row
        .container.section
          ul.nav.nav-tabs.nav-justified
            li
              = link_to "所有", articles_path
            li
              = link_to "新聞稿", presses_articles_path
            li.active
              = link_to "活動", activities_articles_path
            li
              = link_to "評論", comments_articles_path
            li
              = link_to "電子報", epapers_articles_path
            li
              = link_to "書籍", books_articles_path
      h1.title.text-center 活動
      .separator
      .masonry-grid.row
        - @articles.each do |a|
          = render partial: 'shared/article_block', locals: { a: a }
  .row.text-center
    .col-md-10.col-md-offset-1
      = paginate @articles

app/views/articles/books.html.slim
.white-bg.object-non-visible data-animation-effect="fadeInUpSmall" data-effect-delay="100"
  .container
    .row.col-md-12
      .row
        .container.section
          ul.nav.nav-tabs.nav-justified
            li
              = link_to "所有", articles_path
            li
              = link_to "新聞稿", presses_articles_path
            li
              = link_to "活動", activities_articles_path
            li
              = link_to "評論", comments_articles_path
            li
              = link_to "電子報", epapers_articles_path
            li.active
              = link_to "書籍", books_articles_path
      h1.title.text-center 書籍
      .separator
      .masonry-grid.row
        - @articles.each do |a|
          = render partial: 'shared/article_block', locals: { a: a }
  .row.text-center
    .col-md-10.col-md-offset-1
      = paginate @articles

app/views/articles/comments.html.slim
.white-bg.object-non-visible data-animation-effect="fadeInUpSmall" data-effect-delay="100"
  .container
    .row.col-md-12
      .row
        .container.section
          ul.nav.nav-tabs.nav-justified
            li
              = link_to "所有", articles_path
            li
              = link_to "新聞稿", presses_articles_path
            li
              = link_to "活動", activities_articles_path
            li.active
              = link_to "評論", comments_articles_path
            li
              = link_to "電子報", epapers_articles_path
            li
              = link_to "書籍", books_articles_path
      h1.title.text-center 評論
      .separator
      .masonry-grid.row
        - @articles.each do |a|
          = render partial: 'shared/article_block', locals: { a: a }
  .row.text-center
    .col-md-10.col-md-offset-1
      = paginate @articles

app/views/articles/epapers.html.slim
.white-bg.object-non-visible data-animation-effect="fadeInUpSmall" data-effect-delay="100"
  .container
    .row.col-md-12
      .row
        .container.section
          ul.nav.nav-tabs.nav-justified
            li
              = link_to "所有", articles_path
            li
              = link_to "新聞稿", presses_articles_path
            li
              = link_to "活動", activities_articles_path
            li
              = link_to "評論", comments_articles_path
            li.active
              = link_to "電子報", epapers_articles_path
            li
              = link_to "書籍", books_articles_path
      h1.title.text-center 電子報
      .separator
      .masonry-grid.row
        - @articles.each do |a|
          = render partial: 'shared/article_block', locals: { a: a }
  .row.text-center
    .col-md-10.col-md-offset-1
      = paginate @articles

app/views/articles/index.html.slim
p#notice = notice

.white-bg.object-non-visible data-animation-effect="fadeInUpSmall" data-effect-delay="100"
  .container
    .row.col-md-12
      .row
        .container.section
          ul.nav.nav-tabs.nav-justified
            li.active
              = link_to "所有", articles_path
            li
              = link_to "新聞稿", presses_articles_path
            li
              = link_to "活動", activities_articles_path
            li
              = link_to "評論", comments_articles_path
            li
              = link_to "電子報", epapers_articles_path
            li
              = link_to "書籍", books_articles_path
      .masonry-grid.row
        - @articles.each do |a|
          = render partial: 'shared/article_block', locals: { a: a }

      .row.text-center
        .col-md-10.col-md-offset-1
          = paginate @articles

app/views/articles/presses.html.slim
.white-bg.object-non-visible data-animation-effect="fadeInUpSmall" data-effect-delay="100"
  .container
    .row.col-md-12
      .row
        .container.section
          ul.nav.nav-tabs.nav-justified
            li
              = link_to "所有", articles_path
            li.active
              = link_to "新聞稿", presses_articles_path
            li
              = link_to "活動", activities_articles_path
            li
              = link_to "評論", comments_articles_path
            li
              = link_to "電子報", epapers_articles_path
            li
              = link_to "書籍", books_articles_path
      h1.title.text-center 新聞稿
      .separator
      .masonry-grid.row
        - @articles.each do |a|
          = render partial: 'shared/article_block', locals: { a: a }
      .clearfix
      .text-center
        = paginate @articles

app/views/articles/show.html.slim
section.container
  .container
    .row
      .main.col-md-9
        .masonry-grid.row
          .masonry-grid-item.col-xs-12
            article.clearfix.blogpost
              .blogpost-body
                .post-info
                  span.day = @article.published_at.strftime('%d')
                  span.month = @article.published_at.strftime('%-m月 %Y')
                .row
                  header
                    h2.title = @article.title
                    .submitted
                      i.fa.fa-user.pr-1
                      = @article.author
                  - if @article.youtube_id
                    .embed-responsive.embed-responsive-16by9
                      iframe.embed-responsive-item src="//www.youtube.com/embed/#{@article.youtube_id}?rel=0&wmode=opaque"
                  - elsif @article.slides.present?
                    .owl-carousel.content-slider-with-controls-autoplay
                      - @article.slides.each do |slide|
                        = image_tag(slide.image, alt: "", class: "embed-responsive-item")
                  - elsif @article.image.blank?
                    .embed-responsive.embed-responsive-16by9
                      = image_tag("jrf-img.png", alt: "", class: "embed-responsive-item")
                  - else
                    .embed-responsive.embed-responsive-16by9
                      = image_tag(@article.image, alt: "", class: "embed-responsive-item")
        div
          = @article.content.try(:html_safe)
        #disqus_thread
      aside.col-md-3
        .sidebar
          .block.clearfix
            h3.title
              i.fa.fa-tags
              | 關鍵字
            - @article.keywords.each do |k|
              .tags-cloud
                .tag
                  = link_to k.name, keyword_path(k)
          .block.clearfix
            - if @related_articles.any?
              h3.title
                i.fa.fa-comments
                | 相關訊息
              .separator
              - @related_articles.each do |a|
                = render partial: 'shared/article_side_block', locals: { a: a }
            h3.title
              i.fa.fa-bullhorn
              | 最新訊息
            .separator
            - @lastest_articles.each do |a|
              = render partial: 'shared/article_side_block', locals: { a: a }

app/views/articles/videos.html.slim
.white-bg.object-non-visible data-animation-effect="fadeInUpSmall" data-effect-delay="100" 
  .container
    .row.col-md-12
      .masonry-grid.row
        - @articles.each do |a|
          = render partial: 'shared/article_block', locals: { a: a }
    .row.text-center
        .col-md-10.col-md-offset-1
          = paginate @articles