config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  root 'static_pages#home'
  match '/about',     to: 'static_pages#about',     via: 'get'
  match '/donate',    to: 'static_pages#donate',    via: 'get'
  match '/search',    to: 'static_pages#search',    via: 'get'
  match '/thanks',    to: 'static_pages#thanks',    via: 'get'
  match '/feed',      to: 'static_pages#feed',      format: 'atom', via: 'get'
  match '/instant_articles', to: 'static_pages#instant_articles',      format: 'rss', via: 'get'
  match "/sitemap",   to: 'static_pages#sitemap',   format: 'xml',  via: 'get'

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  resources :articles, only: [:show, :index] do
    get :presses, on: :collection
    get :activities, on: :collection
    get :comments, on: :collection
    get :epapers, on: :collection
    get :books, on: :collection
  end
  resources :keywords, only: [:show]
  resources :epapers, only: [:show, :index]
  namespace :admin do
    root 'admins#index',             via: 'get', as: 'admin'
    resources :articles, except: [:show]
    resources :users, only: [:index, :update]
    resources :catalogs, except: [:show] do
      put :sort, on: :collection
    end
    resources :categories, except: [:show] do
      put :sort, on: :collection
    end
    resources :keywords, except: [:show] do
      get :order, on: :collection
      get :show_order, on: :collection
      put :sort,  on: :collection
      put :show_sort,  on: :collection
      resources :faqs, only: [:index]
    end
    match 'faqs/sort',   to: 'faqs#sort',   via: 'put'
    match 'slides/sort', to: 'slides#sort', via: 'put'
  end

  namespace :api, defaults: { format: 'json' } do
    resources :articles, only: [:show, :index]
    resources :keywords, only: [:show, :index]
    resources :catalogs, only: [:show, :index]
  end

  match "/404" => "errors#error404", via: [ :get, :post, :patch, :delete ], as: 'not_found'
  match "/422" => "errors#error422", via: [ :get, :post, :patch, :delete ]
  match "/500" => "errors#error500", via: [ :get, :post, :patch, :delete ]

  get '/api' => redirect('/swagger/dist/index.html?url=/apidocs/api-docs.json')

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :keywords
  belongs_to :catalog
  validates_presence_of :name, message: '請填寫分類名稱'
  validates_presence_of :catalog_id, message: '請選擇主分類'
  scope :published, -> { where(published: true) }
  default_scope { order(position: :asc) }
  before_save :set_position
  validates_uniqueness_of :name, message: '請確認名稱沒有重複'

  def full_name
    "#{self.catalog.name} > #{self.name}"
  end

  def set_position
    self.position ||= Category.maximum("position").to_i + 1
  end

  def chunk_keywords
    unless self.keywords.published.blank?
      max_length = ( self.keywords.published.length + self.width - 1 ) / self.width
      self.keywords.published.each_slice(max_length).to_a
    else
      []
    end
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  before_action :set_category, except: [:index, :new, :sort]

  # GET /categories
  def index
    @q = Category.search(params[:q])
    @categories = @q.result(distinct: true).page(params[:page])
    set_meta_tags({
      title: "次分類管理"
    })
  end

  # GET /categories/1
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
    set_meta_tags({
      title: "新增次分類"
    })
  end

  # GET /categories/1/edit
  def edit
    set_meta_tags({
      title: "編輯次分類"
    })
  end

  # POST /categories
  def create
    if @category.save
      redirect_to admin_categories_url, notice: '次分類建立成功'
    else
      render :new
    end
  end

  # PATCH/PUT /categories/1
  def update
    if @category.update(category_params)
      redirect_to admin_categories_url, notice: '次分類更新成功'
    else
      render :edit
    end
  end

  # DELETE /categories/1
  def destroy
    @category.destroy
    redirect_to admin_categories_url, notice: '次分類已刪除'
  end

  def sort
    category_params[:order].each do |key,value|
      Category.find(value[:id]).update_attribute(:position, value[:position])
      #Category.find(value[:id]).update_attribute(:catalog_id, value[:catalog_id])
    end
    render nothing: true
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = params[:id] ? Category.find(params[:id]) : Category.new(category_params)
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def category_params
    params.require(:category).permit(:name, :published, :position, :width, :catalog_id, :position, {order: [:id, :position, :catalog_id]})
  end
end

app/views/admin/categories/_form.html.slim
.form-group
  = f.input :name, label: '次目錄名稱', required: true, input_html: { class: 'form-control' }
.form-group
  = f.association :catalog, label: '在哪個主目錄下？', label_method: :name, value_method: :id, include_blank: false 
.form-group
  = f.input :published, as: :boolean, label: '允許發布'
.form-group
  = f.input :width, label: "寬度", collection: [['1', 1], ['2', 2]], input_html: { class: 'form-control' }, include_blank: false  
= f.button :submit, "儲存", class: "btn btn-default"

app/views/admin/categories/edit.html.slim
h1.text-center 修改次目錄
pre
  | 目錄名稱不宜過長，
  br
  | 將滑鼠移到專案名稱上，按住滑鼠上下拖曳到要的位置後放開即可調整排序
= simple_form_for @category, url: admin_category_path(@category), method: :put do |f|
  = render :partial => 'form', :locals => { :f => f }

app/views/admin/categories/index.html.slim
h1.text-center 修改/刪除次目錄
pre
  | 若次目錄內有專案則無法進行刪除！
  br
  | 將滑鼠移到次目錄名稱上，按住滑鼠上下拖曳到要的位置後放開即可調整排序
table.table
  thead
    tr
      th 主目錄
      th 次目錄
  tbody
    - @catalogs.each do |c|
      tr
        td = c.name
        td
          .sortable-category data-id="#{c.id}"
            - c.categories.each do |cc|
              .panel.panel-default.gray-bg data-id="#{cc.id}"
                .row
                  .col-xs-6 = cc.name
                  .col-xs-6.text-right
                    = link_to '編輯', edit_admin_category_path(cc), class: "btn radius btn-white btn-sm"
                    = link_to '刪除', admin_category_path(cc), method: :delete, data: { confirm: '確認要刪除嗎？' }, class: "btn radius btn-default btn-sm"

app/views/admin/categories/new.html.slim
h1.text-center 新增次目錄
pre
  | 目錄名稱不宜過長，
  br
  | 將滑鼠移到專案名稱上，按住滑鼠上下拖曳到要的位置後放開即可調整排序
= simple_form_for @category, url: admin_categories_path do |f|
  = render :partial => 'form', :locals => { :f => f }